//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAPI.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModAPI.Common.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to the ModAPI DLLs is available. It includes new features and bugfixes, and is required to use newer mods. Would you like to install it now?
        ///
        ///Current Launcher Kit version: $CURRENTLK$
        ///Current ModAPI DLLs version: $CURRENTDLLS$
        ///New ModAPI DLLs version: $NEWDLLS$.
        /// </summary>
        public static string DllsUpdateAvailable {
            get {
                return ResourceManager.GetString("DllsUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModAPI DLLs Update Available.
        /// </summary>
        public static string DllsUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("DllsUpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close Spore before using the Launcher Kit again.
        ///
        ///If you have just closed Spore, wait a moment for the game to fully exit. If you continue to get this error, please restart your computer..
        /// </summary>
        public static string GameAlreadyRunning {
            get {
                return ResourceManager.GetString("GameAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game already running.
        /// </summary>
        public static string GameAlreadyRunningTitle {
            get {
                return ResourceManager.GetString("GameAlreadyRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spore or Spore Galactic Adventures was not found.
        ///
        ///Both Spore and Spore Galactic Adventures must be installed from disc, EA App, Steam, or GOG.
        ///
        ///Please see https://launcherkit.sporecommunity.com/support for further help..
        /// </summary>
        public static string GameNotFound {
            get {
                return ResourceManager.GetString("GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not found.
        /// </summary>
        public static string GameNotFoundTitle {
            get {
                return ResourceManager.GetString("GameNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path specified does not exist or is invalid..
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to the Spore ModAPI Launcher Kit is now available. Would you like to install it now?
        ///
        ///Current Launcher Kit version: $CURRENTLK$
        ///New Launcher Kit version: $NEWLKS$.
        /// </summary>
        public static string LKUpdateAvailable {
            get {
                return ResourceManager.GetString("LKUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Kit Update Available.
        /// </summary>
        public static string LKUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("LKUpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please launch Spore Galactic Adventures once from Steam. This will complete the installation of the game, and allow the Launcher Kit to work.
        ///
        ///Afterwards, always use the ModAPI Launcher to play the game.
        ///
        ///If you continue to get this message, or the game is not installed from Steam, then the game is likely not installed properly. Please see https://launcherkit.sporecommunity.com/support for further help..
        /// </summary>
        public static string SteamDownloadedButNotLaunched {
            get {
                return ResourceManager.GetString("SteamDownloadedButNotLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam installation not completed.
        /// </summary>
        public static string SteamDownloadedButNotLaunchedTitle {
            get {
                return ResourceManager.GetString("SteamDownloadedButNotLaunchedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Launcher Kit could not connect to the update service. Try again in a few minutes, or check https://launcherkit.sporecommunity.com/support for help..
        /// </summary>
        public static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Kit Update.
        /// </summary>
        public static string UpdateCheckFailedTitle {
            get {
                return ResourceManager.GetString("UpdateCheckFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModAPI DLLs are updating to version .
        /// </summary>
        public static string UpdatingDllsDialog {
            get {
                return ResourceManager.GetString("UpdatingDllsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModAPI DLLs Updating.
        /// </summary>
        public static string UpdatingDllsDialogTitle {
            get {
                return ResourceManager.GetString("UpdatingDllsDialogTitle", resourceCulture);
            }
        }
    }
}
