//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAPI_Installers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModAPI_Installers.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galactic Adventures was not found..
        /// </summary>
        public static string GalacticAdventuresNotFound {
            get {
                return ResourceManager.GetString("GalacticAdventuresNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galactic Adventures was not found. Please specify the installation folder manually (usually called SPORE_EP1 or SPORE Galactic Adventures)..
        /// </summary>
        public static string GalacticAdventuresNotFoundSpecifyManual {
            get {
                return ResourceManager.GetString("GalacticAdventuresNotFoundSpecifyManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path specified does not exist or is invalid..
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        public static string InvalidPathTitle {
            get {
                return ResourceManager.GetString("InvalidPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spore was not found..
        /// </summary>
        public static string SporeNotFound {
            get {
                return ResourceManager.GetString("SporeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spore was not found. Please specify the installation folder manually (usually called SPORE)..
        /// </summary>
        public static string SporeNotFoundSpecifyManual {
            get {
                return ResourceManager.GetString("SporeNotFoundSpecifyManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam was not found..
        /// </summary>
        public static string SteamNotFound {
            get {
                return ResourceManager.GetString("SteamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam was not found. Please specify the installation folder manually (usually C:\Program Files (x86)\Steam)..
        /// </summary>
        public static string SteamNotFoundSpecifyManual {
            get {
                return ResourceManager.GetString("SteamNotFoundSpecifyManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access. Try executing the launcher with Administrator Privileges (Right-click &gt; &quot;Run as Administrator&quot;)..
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unauthorized access.
        /// </summary>
        public static string UnauthorizedAccessTitle {
            get {
                return ResourceManager.GetString("UnauthorizedAccessTitle", resourceCulture);
            }
        }
    }
}
