//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spore_ModAPI_Easy_Installer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spore_ModAPI_Easy_Installer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file.
        /// </summary>
        internal static string CopyingFile {
            get {
                return ResourceManager.GetString("CopyingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid mod file. Only .sporemod and .package files are supported..
        /// </summary>
        internal static string ErrorUnsupportedFile {
            get {
                return ResourceManager.GetString("ErrorUnsupportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting file.
        /// </summary>
        internal static string ExtractingFile {
            get {
                return ResourceManager.GetString("ExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spore Mod (*.sporemod)|*.sporemod|Spore PACKAGE file (*.package)|*.package|All supported files|*.sporemod;*.package.
        /// </summary>
        internal static string FileChooserFilter {
            get {
                return ResourceManager.GetString("FileChooserFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the mod to be installed.
        /// </summary>
        internal static string FileChooserTitle {
            get {
                return ResourceManager.GetString("FileChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed.
        /// </summary>
        internal static string InstallationCompleted {
            get {
                return ResourceManager.GetString("InstallationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod &quot;$MODNAME$&quot; is being installed, please wait....
        /// </summary>
        internal static string InstallingMod {
            get {
                return ResourceManager.GetString("InstallingMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing mod....
        /// </summary>
        internal static string InstallingModTitle {
            get {
                return ResourceManager.GetString("InstallingModTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cannot be installed, because it specifies an invalid version of the ModAPI DLLs. Please ask the mod developer for help..
        /// </summary>
        internal static string InvalidDllVersion {
            get {
                return ResourceManager.GetString("InvalidDllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: mod cannot be installed.
        /// </summary>
        internal static string InvalidDllVersionTitle {
            get {
                return ResourceManager.GetString("InvalidDllVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of the mod &quot;$MODNAME$&quot; was cancelled..
        /// </summary>
        internal static string ModCancelled {
            get {
                return ResourceManager.GetString("ModCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod &quot;$MODNAME$&quot; has been installed..
        /// </summary>
        internal static string ModInstalled {
            get {
                return ResourceManager.GetString("ModInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when installing the mod &quot;$MODNAME$&quot;. This mod was not installed..
        /// </summary>
        internal static string ModNotInstalled {
            get {
                return ResourceManager.GetString("ModNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cannot be installed, because it requires a newer version of the ModAPI DLLs. Please restart the launcher and allow it to update.
        ///
        ///Required ModAPI DLLs version: $REQUIREDVERSION$ or higher.
        /// </summary>
        internal static string OutdatedDllVersion {
            get {
                return ResourceManager.GetString("OutdatedDllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated ModAPI DLLs version.
        /// </summary>
        internal static string OutdatedDllVersionTitle {
            get {
                return ResourceManager.GetString("OutdatedDllVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Easy Installer does not currently have permission to install or change mods. You may need to right-click the Easy Installer and &quot;Run as Administrator&quot;..
        /// </summary>
        internal static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
    }
}
