//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporeModAPI_Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SporeModAPI_Launcher.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not apply the Steam fix. To apply it, you can do one of these two options:
        /// - Re-execute the Launcher with Administrator Privileges.
        ///or
        /// - Create a file called &apos;steam_appid.txt&apos;, with the numbers &apos;17390&apos; inside, in the folder $PATH$.
        /// </summary>
        public static string CannotApplySteamFix {
            get {
                return ResourceManager.GetString("CannotApplySteamFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not apply the Steam fix.
        /// </summary>
        public static string CannotApplySteamFixTitle {
            get {
                return ResourceManager.GetString("CannotApplySteamFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your game version could not be detected. Please choose your version:.
        /// </summary>
        public static string ChooseGameVersion {
            get {
                return ResourceManager.GetString("ChooseGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your game version.
        /// </summary>
        public static string ChooseGameVersionTitle {
            get {
                return ResourceManager.GetString("ChooseGameVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete. Launch game now?.
        /// </summary>
        public static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        public static string DownloadCompleteTitle {
            get {
                return ResourceManager.GetString("DownloadCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading ModAPI Fix.
        /// </summary>
        public static string DownloadFixTitle {
            get {
                return ResourceManager.GetString("DownloadFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin users need to download an additional file in order for ModAPI to work. If you press OK, the launcher will download and apply this additional file..
        /// </summary>
        public static string DownloadOriginFix {
            get {
                return ResourceManager.GetString("DownloadOriginFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting files....
        /// </summary>
        public static string ExtractingFiles {
            get {
                return ResourceManager.GetString("ExtractingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File needed.
        /// </summary>
        public static string FileNeeded {
            get {
                return ResourceManager.GetString("FileNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while starting or injecting your mods into Spore Galactic Adventures. The game may start, but some mods will not work correctly.\nIf you see this message, please report the issue, along with a screenshot of this MessageBox. A forum thread where you may do so should open once this MessageBox is closed, but if this does not occur, you can also find the thread at:.
        /// </summary>
        public static string GalacticAdventuresNotExecuted {
            get {
                return ResourceManager.GetString("GalacticAdventuresNotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of Dark Injection you have installed (Dark Injection 9.r Public Beta 2.3.0) is not compatible with this update to the ModAPI Launcher Kit. Please update to a later version of Dark Injection. We don&apos;t believe in forcing updates onto anyone, but unfortunately, this was the price to pay to resolve some of the rampant issues some users have faced when using the ModAPI Launcher Kit.\n\nUpon closing this MessageBox, the Dark Injection webpage will open in your default internet browser. You&apos;ll be able  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IncompatibleDarkInjection {
            get {
                return ResourceManager.GetString("IncompatibleDarkInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Mod Detected.
        /// </summary>
        public static string IncompatibleMod {
            get {
                return ResourceManager.GetString("IncompatibleMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModAPI needs Galactic Adventures and (at least) Spore patch 1.5.1 to work correctly. If your game crashes or ModAPI mods do not work, install Galactic Adventures and download the latest patch from spore.com.
        /// </summary>
        public static string MightNotWork {
            get {
                return ResourceManager.GetString("MightNotWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModAPI might not work.
        /// </summary>
        public static string MightNotWorkTitle {
            get {
                return ResourceManager.GetString("MightNotWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process thread could not be resumed..
        /// </summary>
        public static string ProcessNotResumed {
            get {
                return ResourceManager.GetString("ProcessNotResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start process..
        /// </summary>
        public static string ProcessNotStarted {
            get {
                return ResourceManager.GetString("ProcessNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have the most recent patch (released on March 20th, 2017 if nothing newer is out since) installed?.
        /// </summary>
        public static string SteamLastVersion {
            get {
                return ResourceManager.GetString("SteamLastVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have the latest version?.
        /// </summary>
        public static string SteamLastVersionTitle {
            get {
                return ResourceManager.GetString("SteamLastVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following mods cannot be loaded because they require a greater version of the ModAPI Core DLLs.
        ///Please, restart the launcher and allow it to update.
        ///.
        /// </summary>
        public static string UnsupportedDllVersion {
            get {
                return ResourceManager.GetString("UnsupportedDllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: some mods could not be loaded.
        /// </summary>
        public static string UnsupportedDllVersionTitle {
            get {
                return ResourceManager.GetString("UnsupportedDllVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version could not be detected, ModAPI won&apos;t load..
        /// </summary>
        public static string VersionNotDetected {
            get {
                return ResourceManager.GetString("VersionNotDetected", resourceCulture);
            }
        }
    }
}
