//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporeModAPI_Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SporeModAPI_Launcher.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Launcher Kit needs to download a compatibility fix for your current game version. Do you want to continue?.
        /// </summary>
        public static string CompatibilityFixDownload {
            get {
                return ResourceManager.GetString("CompatibilityFixDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading compatibility fix.
        /// </summary>
        public static string CompatibilityFixDownloadTitle {
            get {
                return ResourceManager.GetString("CompatibilityFixDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Launcher Kit could not apply an EA App compatibility fix. Please try the following:
        ///- Ensure you have a stable internet connection
        /// - Right click the Spore ModAPI Launcher and &quot;Run as Administrator&quot; once, to allow the fix to be applied, then exit the game and run it normally.
        /// </summary>
        public static string CompatibilityFixErrorEA {
            get {
                return ResourceManager.GetString("CompatibilityFixErrorEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Launcher Kit could not apply a Steam compatibility fix. To apply it, you can do one of these two options:
        /// - Right click the Spore ModAPI Launcher and &quot;Run as Administrator&quot; once, to allow the fix to be applied, then exit the game and run it normally
        ///or
        /// - Create a file called &apos;steam_appid.txt&apos;, with the numbers &apos;17390&apos; inside, in the folder $PATH$.
        /// </summary>
        public static string CompatibilityFixErrorSteam {
            get {
                return ResourceManager.GetString("CompatibilityFixErrorSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not apply compatibility fix.
        /// </summary>
        public static string CompatibilityFixErrorTitle {
            get {
                return ResourceManager.GetString("CompatibilityFixErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while starting or loading your mods into Spore. The game may start, but some mods will not work correctly.
        ///
        ///Please see https://launcherkit.sporecommunity.com/support for further help..
        /// </summary>
        public static string GameNotExecuted {
            get {
                return ResourceManager.GetString("GameNotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current game version is not compatible with the LAA/4GB patch. The game may not launch.
        ///
        ///You can do one of the following:
        ///- Downgrade to a game version that is compatible with the LAA/4GB patch
        ///- Remove the LAA/4GB patch using the same tool used to apply it
        ///- Remove the LAA/4GB patch by verifying the game files for Spore Galactic Adventures
        ///
        ///The LAA/4GB patch is not required to use mods, but may help improve game stability.
        ///
        ///Please see https://launcherkit.sporecommunity.com/support for further [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LAAUnsupported {
            get {
                return ResourceManager.GetString("LAAUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAA/4GB Patch Incompatible.
        /// </summary>
        public static string LAAUnsupportedTitle {
            get {
                return ResourceManager.GetString("LAAUnsupportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spore ModAPI Launcher Error.
        /// </summary>
        public static string LauncherError {
            get {
                return ResourceManager.GetString("LauncherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process thread could not be resumed..
        /// </summary>
        public static string ProcessNotResumed {
            get {
                return ResourceManager.GetString("ProcessNotResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start process..
        /// </summary>
        public static string ProcessNotStarted {
            get {
                return ResourceManager.GetString("ProcessNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running the Spore ModAPI Launcher as Administrator (by right-clicking and selecting &quot;Run as Administrator&quot;) is not recommended.
        ///
        ///This can be a security risk and can also cause problems with game functionality. You may be unable to load creations into Spore by dragging their PNGs into the game window.
        ///
        ///Are you sure you want to continue?.
        /// </summary>
        public static string RunAsAdminWarning {
            get {
                return ResourceManager.GetString("RunAsAdminWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SporeModLoader has been detected. Running the Launcher Kit alongside SporeModLoader is unsupported.
        ///
        ///You have the the following options:
        ///- Remove SporeModLoader to use the Launcher Kit by removing $PATH$
        ///- Use SporeModLoader instead of the Launcher Kit.
        /// </summary>
        public static string SporeModLoaderDetected {
            get {
                return ResourceManager.GetString("SporeModLoaderDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SporeModLoader detected.
        /// </summary>
        public static string SporeModLoaderDetectedTitle {
            get {
                return ResourceManager.GetString("SporeModLoaderDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current Spore game version is not compatible with this Launcher Kit version.
        ///
        ///Both Spore and Spore Galactic Adventures must be installed from disc, EA App, Steam, or GOG.
        ///
        ///If you downloaded the game from EA App, Steam, or GOG, please ensure the game is up-to-date.
        ///
        ///Please see https://launcherkit.sporecommunity.com/support for further help..
        /// </summary>
        public static string UnsupportedSporeVersion {
            get {
                return ResourceManager.GetString("UnsupportedSporeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Spore version.
        /// </summary>
        public static string UnsupportedSporeVersionTitle {
            get {
                return ResourceManager.GetString("UnsupportedSporeVersionTitle", resourceCulture);
            }
        }
    }
}
